
---

  ## .github/workflows/ci.yml
  
  ```yaml
  name: CI
  
  # 1. Trigger ad ogni push sul branch main
  on:
    push:
      branches: [ main ]
  
  jobs:
    test:
      # 2. Esecuzione su runner Ubuntu
      runs-on: ubuntu-latest
  
      steps:
        # 3. Checkout del codice
        - name: Checkout repository
          uses: actions/checkout@v4
  
        # 4. Setup dell’ambiente Node.js
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'
  
        # 5. Installazione delle dipendenze
        - name: Install dependencies
          run: npm ci
  
        # 6. Esecuzione dei test con coverage
        - name: Run tests
          run: npm test
  
        # 7. (Opzionale) Pubblicazione dei report di coverage su Codecov
        - name: Upload coverage report to Codecov
          uses: codecov/codecov-action@v3
          with:
            files: ./coverage/lcov.info
            flags: unit
            fail_ci_if_error: true
  