name: CI

# 1. Trigger ad ogni push sul repository
on:
  push:
    branches:
      - main

jobs:
  test:
    # 2. Runner Ubuntu preconfigurato
    runs-on: ubuntu-latest

    steps:
      # 3. Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4

      # 4. Setup Node.js (versione LTS)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # 5. Installazione dipendenze in modo pulito
      - name: Install dependencies
        run: npm ci

      # 6. Esecuzione dei test Jest
      - name: Run tests
        run: npm test
